#!/bin/bash

if [ -z "" -o "yes" = no ];
then

cat <<EOF
test_ignore=yes
EOF
  
exit

fi

source /home/remixman/Desktop/mcxx/tests/config/mercurium-libraries

cat <<EOF
MCC="/home/remixman/Desktop/mcxx/src/driver/mcxx --output-dir=/home/remixman/Desktop/mcxx/tests --profile=mcc --config-dir=/home/remixman/Desktop/mcxx/config --verbose"
MCXX="/home/remixman/Desktop/mcxx/src/driver/mcxx --output-dir=/home/remixman/Desktop/mcxx/tests --profile=mcxx --config-dir=/home/remixman/Desktop/mcxx/config --verbose"
SSCC="/home/remixman/Desktop/mcxx/src/driver/mcxx --output-dir=/home/remixman/Desktop/mcxx/tests --profile=sscc --config-dir=/home/remixman/Desktop/mcxx/config --verbose"
SSCXX="/home/remixman/Desktop/mcxx/src/driver/mcxx --output-dir=/home/remixman/Desktop/mcxx/tests --profile=sscxx --config-dir=/home/remixman/Desktop/mcxx/config --verbose"
EOF

if [ ! -z "" ];
then

# compile_versions="\${compile_versions} nanox_cuda"
cat <<EOF

test_CC_cuda_omp="\${MCC}"
test_CXX_cuda_omp="\${MCXX}"

test_CFLAGS_cuda_omp="--openmpt"
test_CXXFLAGS_cuda_omp="--openmpt"

test_CC_cuda_sscc="\${SSCC}"
test_CXX_cuda_sscc="\${SSCXX}"

test_CFLAGS_cuda_sscc=""
test_CXXFLAGS_cuda_sscc=""
EOF

fi

cat <<EOF
test_nolink=yes
EOF
