#!/bin/bash

source /home/remixman/Desktop/mcxx/tests/config/mercurium-libraries

cat <<EOF
MCXX="/home/remixman/Desktop/mcxx/src/driver/mcxx --output-dir=/home/remixman/Desktop/mcxx/tests --config-dir=/home/remixman/Desktop/mcxx/config --verbose"
test_CC="\${MCXX} --profile=plaincc"
test_CXX="\${MCXX} --profile=plaincxx"
test_noexec=yes
test_CFLAGS="-y --typecheck"
test_CXXFLAGS="-y --typecheck"
EOF
